name: Dependabot Auto-merge

on:
  pull_request:

permissions:
  contents: read

jobs:
  auto-merge:
    uses: cuioss/cuioss-organization/.github/workflows/reusable-dependabot-auto-merge.yml@9cffe3a2febb07d668784a1257b025101228754d # v0.27.0
    permissions:
      contents: write
      pull-requests: write
