name: Dependabot Auto-merge

on:
  pull_request:

permissions:
  contents: read

jobs:
  auto-merge:
    uses: cuioss/cuioss-organization/.github/workflows/reusable-dependabot-auto-merge.yml@5fb6e07834411caa78a0eefe6e6a0554c9a957e6 # v0.32.0
    permissions:
      contents: write
      pull-requests: write
