name: Dependabot Auto-merge

on:
  pull_request:

permissions:
  contents: read

jobs:
  auto-merge:
    uses: cuioss/cuioss-organization/.github/workflows/reusable-dependabot-auto-merge.yml@e750788f3f5c718d945dc504fab4975bbb705404 # v0.16.0
    permissions:
      contents: write
      pull-requests: write
