# Example: Copy this to your repo as .github/workflows/scorecards.yml
name: Scorecard supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: '20 7 * * 2'
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  analysis:
    uses: cuioss/cuioss-organization/.github/workflows/reusable-scorecards.yml@9ea25d1cc6599d24a0f2333330b112c627f58688 # v0.9.0
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
      issues: read
      pull-requests: read
      checks: read
