# Example: Copy this to your repo as .github/workflows/scorecards.yml
name: Scorecard supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: '20 7 * * 2'
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  analysis:
    uses: cuioss/cuioss-organization/.github/workflows/reusable-scorecards.yml@0af17b4211b2db37c3bc9b5f316f0c534c3ee8d5 # v0.6.8
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
      issues: read
      pull-requests: read
      checks: read
